// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dataaccess;

#nullable disable

namespace dataaccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("dataaccess.Entities.Board", b =>
                {
                    b.Property<string>("BoardID")
                        .HasColumnType("text");

                    b.Property<int>("BoardSize")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.Property<int>("WeeksPurchased")
                        .HasColumnType("integer");

                    b.Property<bool>("Win")
                        .HasColumnType("boolean");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("BoardID");

                    b.HasIndex("UserID");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("dataaccess.Entities.BoardNumber", b =>
                {
                    b.Property<string>("BoardNumberID")
                        .HasColumnType("text");

                    b.Property<string>("BoardID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("BoardNumberID");

                    b.HasIndex("BoardID");

                    b.ToTable("BoardNumber");
                });

            modelBuilder.Entity("dataaccess.Entities.Transaction", b =>
                {
                    b.Property<string>("TransactionID")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<bool>("Pending")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TransactionID");

                    b.HasIndex("UserID");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("dataaccess.Entities.User", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("text");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Firstlogin")
                        .HasColumnType("boolean");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubscriptionExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("dataaccess.Entities.WinningBoard", b =>
                {
                    b.Property<string>("WinningBoardID")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.Property<int>("WeekYear")
                        .HasColumnType("integer");

                    b.HasKey("WinningBoardID");

                    b.ToTable("WinningBoards");
                });

            modelBuilder.Entity("dataaccess.Entities.WinningNumber", b =>
                {
                    b.Property<string>("WinningNumberID")
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("WinningBoardID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WinningNumberID");

                    b.HasIndex("WinningBoardID");

                    b.ToTable("WinningNumbers");
                });

            modelBuilder.Entity("dataaccess.Entities.Board", b =>
                {
                    b.HasOne("dataaccess.Entities.User", "User")
                        .WithMany("Boards")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("dataaccess.Entities.BoardNumber", b =>
                {
                    b.HasOne("dataaccess.Entities.Board", null)
                        .WithMany("Numbers")
                        .HasForeignKey("BoardID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dataaccess.Entities.Transaction", b =>
                {
                    b.HasOne("dataaccess.Entities.User", null)
                        .WithMany("Transactions")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dataaccess.Entities.WinningNumber", b =>
                {
                    b.HasOne("dataaccess.Entities.WinningBoard", "WinningBoard")
                        .WithMany("WinningNumbers")
                        .HasForeignKey("WinningBoardID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WinningBoard");
                });

            modelBuilder.Entity("dataaccess.Entities.Board", b =>
                {
                    b.Navigation("Numbers");
                });

            modelBuilder.Entity("dataaccess.Entities.User", b =>
                {
                    b.Navigation("Boards");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("dataaccess.Entities.WinningBoard", b =>
                {
                    b.Navigation("WinningNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
